PROCESSED_DIR_NAME = "Processed"

RAW_DIR_NAME = "Raw"

MANUAL_HOOK = "Manual"

RESULTS_DIR_NAME = "results"

STATIC_METRIC_LOCATION = "qc"

PIPELINE_NGS = "Ngs"
PIPELINE_MANUAL = MANUAL_HOOK

STUDY_TYPE_CANCER = "cancer"
STUDY_TYPES = (
    (STUDY_TYPE_CANCER, STUDY_TYPE_CANCER),
)
